export const sidebarRoutes = [
    {
        name:"Assets",
        key:"assets",
    },
    {
        name:"Investments",
        key:"investment",
    },
    {
        name:"Savings",
        key:"savings",
    },
    {
        name:"Lent",
        key:"lent",
    },
    {
        name:"Loans",
        key:"loan",
    }
]